-- Rocío Rial Garrido	DNI: 77481582X

USE EXCOCINA25

-- 1. 
SELECT R.NOME, ('(' + (LEFT(R.TELEFONO, 3)) + ') ' + SUBSTRING(R.TELEFONO, 4, 6) + '.' + SUBSTRING(R.TELEFONO, 7, 9)) AS TELEFONO, 
       (DATEDIFF(MONTH, R.DATAINAGURACION, GETDATE())) AS TIEMPO_EN_MESES, 
	   (P.NOME + ' ' + P.APELIDO1 + ' ' + P.APELIDO2) AS NOMBRE
FROM RESTAURANTE R INNER JOIN COCINERO C ON R.COD_COCINERO = C.CODIGO
				   INNER JOIN PERSONAL P ON P.CODIGO = C.CODIGO
				   LEFT JOIN LIBRO L ON L.COD_COCINERO = C.CODIGO
WHERE DATEDIFF(YEAR, P.DATA_NACEMENTO, GETDATE()) > 10
AND L.COD_COCINERO IS NULL
ORDER BY LEN(R.NOME) 

-- 2. 
SELECT (PR.CODIGO + '-' + PR.NOME) AS PROVINCIA, COUNT(P.CODIGO) AS NUM_COCINERAS_CHEF
FROM PROVINCIA PR INNER JOIN PERSONAL P ON PR.CODIGO = P.COD_PROVINCIA
				  INNER JOIN COCINERO C ON P.CODIGO = C.CODIGO
WHERE P.SEXO = 'M' AND YEAR(P.DATA_NACEMENTO) BETWEEN 1960 AND 2000
GROUP BY PR.CODIGO, PR.NOME
ORDER BY NUM_COCINERAS_CHEF DESC, PR.NOME

-- 3. 
IF EXISTS copiaLIBRO
DROP TABLE
THEN CREATE TABLE
UPDATE copiaLIBRO

SELECT AVG(PVP_REFERENCIA) AS MEDIA
FROM LIBRO

SELECT TOP 1 WITH TIES COUNT(RI.COD_INGREDIENTE)
FROM LIBRO L INNER JOIN RECETA REC ON L.CODIGO = REC.CODIGO
			 INNER JOIN RECETA_INGREDIENTE RI ON REC.CODIGO = RI.COD_RECETA
CASE
	WHEN L.PVP_REFERENCIA > MEDIA THEN L.PVP_REFERENCIA = L.PVP_REFERENCIA * 0.10
	ELSE L.PVP_REFERENCIA = L.PVP_REFERENCIA * 0.05
END

-- 4. 
SELECT DISTINCT(P.NOME + ' ' + P.APELIDO1 + ' ' + P.APELIDO2) AS AUXILIAR_COCINA, 
	   ISNULL(P.NOME + ' ' + P.APELIDO1 + ' ' + P.APELIDO2, 'Sin maestro') AS MAESTRO, 
	   P.EMAIL 
FROM PERSONAL P INNER JOIN AUXILIARCOCINA AU ON P.CODIGO = AU.CODIGO
				INNER JOIN TAREA T ON T.CODIGO = AU.CODIGO
WHERE T.TIPO IS LIKE %'limpieza'% AND 
	  P.EMAIL IS NOT LIKE %@gmail.com
			
-- 5.
SELECT P.CODIGO, ('(' + C.TIPO + ') ' + P.NOMBRE + ' ' P.APELIDO1 + ' ' P.APELIDO2) AS NOMBRE,
	   DATEDIFF(YEAR, P.DATA_NACIMIENTO, GETDATE()) AS EDAD
		CASE P.TELEFONOMOVIL
			WHEN P.TELEFONOMOVIL IS NULL THEN P.EMAIL
			ELSE '' 
			END AS CONTACTO,
		FORMAT(P.DATA_NACIMIENTO, 'dd' + 'DE' + datename(MONTH) AS FECHA_CUMPLEAÑOS
FROM PERSONAL P INNER JOIN COCINERO C ON P.CODIGO = C.CODIGO
WHERE DATEDIFF(YEAR, DATA_NACEMENTO, GETDATE()) BETWEEN 30 and 40
ORDER BY EDAD DESC

-- 6 a.
SELECT REC.NOME, REC.TEMPO, COUNT(RI.COD_INGREDIENTE) AS NUM_INGREDIENTES
FROM RECETA REC INNER JOIN RECETA_INGREDIENTE RI ON REC.CODIGO = RI.COD_RECETA
GROUP BY REC.NOME, REC.TEMPO
ORDER BY NUM_INGREDIENTES
-- 6 b. 
SELECT TOP 4 FILEGROUP
FROM RecetaIngredientesGrupo
ORDER BY TEMPO
