-- 73._ ¿Quién es el propietario que posee más pisos de más de 2 habitaciones que no están situados en la zona centro?

-- Usando JOIN
SELECT TOP 1 WITH TIES P.DNI, P.NOMBRE, P.APELLIDO1, P.APELLIDO2, COUNT(*) AS NumPisos
FROM PISO PS
INNER JOIN PROPIETARIO P ON PS.DNIPROPIETARIO = P.DNI
INNER JOIN VIVIENDA V ON PS.CALLE = V.CALLE AND PS.NUMERO = V.NUMERO
WHERE PS.NUMHABITACIONES > 2 AND V.NOMBREZONA <> 'Centro'
GROUP BY P.DNI, P.NOMBRE, P.APELLIDO1, P.APELLIDO2
ORDER BY NumPisos DESC;

-- Alternativa con subconsulta

SELECT TOP 1 WITH TIES DNI, NOMBRE, APELLIDO1, APELLIDO2, COUNT(*) AS NumPisos
FROM PISO P
	INNER JOIN PROPIETARIO ON DNI = DNIPROPIETARIO
WHERE NUMHABITACIONES>2 AND CALLE+CAST(NUMERO AS VARCHAR(3)) IN 
		(SELECT CALLE+CAST(NUMERO AS VARCHAR(3))
		 FROM VIVIENDA
		 WHERE NOMBREZONA <> 'Centro' )
GROUP BY DNI, NOMBRE, APELLIDO1, APELLIDO2
ORDER BY NumPisos DESC

-- ESTÁNDAR

DECLARE @MAXPISOS INT
SET @MAXPISOS=(
SELECT MAX(NUMPISOS)
FROM
	(SELECT COUNT(*) AS NUMPISOS
	 FROM PISO P 
		INNER JOIN VIVIENDA V ON P.CALLE = V.CALLE AND P.NUMERO = V.NUMERO
		INNER JOIN PROPIETARIO PR ON PR.DNI = P.DNIPROPIETARIO
	 WHERE NOMBREZONA <> 'Centro' AND NUMHABITACIONES > 2
	 GROUP BY DNIPROPIETARIO ) AS T)
	 
SELECT DNI, NOMBRE, APELLIDO1, APELLIDO2, COUNT(*) AS NUMPISOS
FROM PISO P
	INNER JOIN PROPIETARIO ON DNI = DNIPROPIETARIO
	INNER JOIN VIVIENDA V ON P.CALLE = V.CALLE AND P.NUMERO = V.NUMERO
WHERE NOMBREZONA <> 'Centro' AND NUMHABITACIONES > 2
GROUP BY DNI, NOMBRE, APELLIDO1, APELLIDO2
HAVING COUNT(*)=@MAXPISOS
	 


-- 74._ Para cada bloque de pisos (calle y número), máximo de metros útiles y habitaciones, sólo si tiene más de 3 pisos

SELECT CALLE, NUMERO,
       MAX(METROSUTILES) AS MaxMetrosUtiles,
       MAX(NUMHABITACIONES) AS MaxHabitaciones
FROM PISO 
GROUP BY CALLE, NUMERO
HAVING COUNT(*) > 3;

-- 75._ Lista de personas con sus viviendas si las tienen, ordenadas por apellidos y nombre

SELECT P.DNI, P.NOMBRE, P.APELLIDO1, P.APELLIDO2, V.CALLE, V.NUMERO, V.TIPOVIVIENDA
FROM PROPIETARIO P
	INNER JOIN PISO PS ON P.DNI = PS.DNIPROPIETARIO
	INNER JOIN VIVIENDA V ON PS.CALLE = V.CALLE AND PS.NUMERO = V.NUMERO
	
UNION

SELECT P.DNI, P.NOMBRE, P.APELLIDO1, P.APELLIDO2, V.CALLE, V.NUMERO, V.TIPOVIVIENDA
FROM PROPIETARIO P
	INNER JOIN CASAPARTICULAR CP ON P.DNI = CP.DNIPROPIETARIO
	INNER JOIN VIVIENDA V ON CP.CALLE = V.CALLE AND CP.NUMERO = V.NUMERO
	
UNION

SELECT DNI, NOMBRE, APELLIDO1, APELLIDO1, NULL, NULL, NULL
FROM PROPIETARIO 
WHERE DNI NOT IN ( SELECT DNIPROPIETARIO FROM PISO
				   UNION
			       SELECT DNIPROPIETARIO FROM CASAPARTICULAR)
ORDER BY APELLIDO1, APELLIDO2, NOMBRE;


-- 76._ ¿Quién es el propietario de la bodega más pequeña?

SELECT TOP 1 WITH TIES P.NOMBRE, P.APELLIDO1, P.APELLIDO2
FROM HUECO H
INNER JOIN PROPIETARIO P ON H.DNIPROPIETARIO = P.DNI
WHERE H.TIPO = 'Bodega'
ORDER BY H.METROS ASC;

-- Sin usar TOP

SELECT P.NOMBRE, P.APELLIDO1, P.APELLIDO2
FROM HUECO H
INNER JOIN PROPIETARIO P ON H.DNIPROPIETARIO = P.DNI
WHERE H.TIPO = 'Bodega'
AND H.METROS = (
    SELECT MIN(METROS)
    FROM HUECO
    WHERE TIPO = 'Bodega'
);

-- 77._ Mujeres con trastero > 10m o garaje < 13m, mostrando datos de la propiedad

SELECT P.DNI, P.NOMBRE + ' ' + P.APELLIDO1 + ' ' + P.APELLIDO2 AS NombreCompleto,
       H.CALLE, H.NUMERO, H.TIPO, H.METROS
FROM PROPIETARIO P
INNER JOIN HUECO H ON P.DNI = H.DNIPROPIETARIO
WHERE P.SEXO = 'M' AND (
      (H.TIPO = 'Trastero' AND H.METROS > 10)
   OR (H.TIPO = 'Garaje' AND H.METROS < 13))
   
UNION

SELECT DNI, NOMBRE + ' ' + APELLIDO1 + ' ' + APELLIDO2 AS NombreCompleto,
	   NULL, NULL, NULL, NULL
FROM PROPIETARIO
WHERE SEXO = 'M'

ORDER BY NombreCompleto

-- 78._ Zona urbana con más propiedades (pisos + casas particulares + huecos)

-- Usando TOP 1

SELECT TOP 1 WITH TIES 
	   NOMBREZONA, COUNT(*) AS TotalPropiedades
FROM (
    SELECT V.NOMBREZONA FROM VIVIENDA V INNER JOIN PISO P ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
    UNION ALL
    SELECT V.NOMBREZONA FROM VIVIENDA V INNER JOIN CASAPARTICULAR C ON V.CALLE = C.CALLE AND V.NUMERO = C.NUMERO
    UNION ALL
    SELECT V.NOMBREZONA FROM VIVIENDA V INNER JOIN HUECO H ON V.CALLE = H.CALLE AND V.NUMERO = H.NUMERO
) AS Propiedades
GROUP BY NOMBREZONA
ORDER BY COUNT(*) DESC;

-- Estándar: sin TOP, usando MAX y HAVING

SELECT NOMBREZONA, COUNT(*) AS TotalPropiedades
FROM (
    SELECT V.NOMBREZONA FROM VIVIENDA V
    INNER JOIN PISO P ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
    UNION ALL
    SELECT V.NOMBREZONA FROM VIVIENDA V
    INNER JOIN CASAPARTICULAR C ON V.CALLE = C.CALLE AND V.NUMERO = C.NUMERO
    UNION ALL
    SELECT V.NOMBREZONA FROM VIVIENDA V
    INNER JOIN HUECO H ON V.CALLE = H.CALLE AND V.NUMERO = H.NUMERO
) AS Propiedades
GROUP BY NOMBREZONA
HAVING COUNT(*) = (
    SELECT MAX(Conteo)
    FROM (
        SELECT COUNT(*) AS Conteo
        FROM (
            SELECT V.NOMBREZONA FROM VIVIENDA V
            INNER JOIN PISO P ON V.CALLE = P.CALLE AND V.NUMERO = P.NUMERO
            UNION ALL
            SELECT V.NOMBREZONA FROM VIVIENDA V
            INNER JOIN CASAPARTICULAR C ON V.CALLE = C.CALLE AND V.NUMERO = C.NUMERO
            UNION ALL
            SELECT V.NOMBREZONA FROM VIVIENDA V
            INNER JOIN HUECO H ON V.CALLE = H.CALLE AND V.NUMERO = H.NUMERO
        ) AS Sub
        GROUP BY NOMBREZONA
    ) AS ConteosZona
);


